### ISSUE TITLE
Enhancement Requests

### ISSUE THREAD

**Issue by brustmlj** [Ariel-Thomas/adventurers-league-log#1]
Hello,

I have just found this web-site and I am finding it useful for adding my Character and DM log entries.  I seems like a site I was about to create for myself.  I was wondering if you are willing to discuss additional features.

Would it be possible to upload pictures of certs received?
Would it be possible to upload signed logs like received at Fai Chen’s?
Would it be possible to create a Game or Session log for the DM?
There is a log for DM rewards this would score the game or session itself
   Date
   Location
   DM info
      Name
      DCI
   Character Info
      Player Name
      Character Name
      Class and Level
      DCI
   XP Awarded
   GP Awarded
   Downtime Awarded
   Renown Awarded
   Magic Item Awarded and Character who received it
   Notes
An XML output option for
   Single Character
   All Characters
   All DM logs
   All Game logs
   All User Data
DM Log Entries
   Add a date used for the character assigned so that the DM awards are properly interlaced into the characters log sheet

I am interested in collaborating.  I hope this message finds you.

Mike

**Comment by Ariel-Thomas** [comment]
Breaking into distinct requests
