### ISSUE TITLE
Players can't join campaign

### ISSUE THREAD

**Issue by th3third** [Ariel-Thomas/adventurers-league-log#100]
I've recently created a campaign (#227) and gave out the player token to my table. They've repeatedly tried to join the campaign, but are getting a "You are not authorized to perform this action." error. I've had this report from two separate players and have confirmed that they are visiting the correct area. They're _not_ going through "Join As DM". The campaign is set to "Users Can Join" so there shouldn't be any issue with them joining.

I attempted to join it myself using my own character and was able to do so successfully.

Any insight into this?

**Comment by Ariel-Thomas** [comment]
So, the only checks in the policy are that the character's user is the current user (they should only be able to select those characters from the list anyway), the campaign exists and that the users_can_join flag is flipped. I'm not seeing any issues joining the campaign myself.

Can you get the affected user and character numbers?

**Comment by Ariel-Thomas** [comment]
Oh, my guess is there's leading or trailing space.

**Comment by th3third** [comment]
One of the players is user #1894. I'm not sure about the character number, but it should be his druid and probably his only one in there.

**Comment by Ariel-Thomas** [comment]
He in fact has two druids. See if you can get a player to try again paying special attention to avoiding spaces. If that doesn't work, I'll go through the process of logging in as them and trying myself.

**Comment by th3third** [comment]
Alright, I'll ask them to check for a leading or trailing space and try again. I have no idea why he has two of them. Shrug.

Thanks!

**Comment by th3third** [comment]
That appears to have done it. Good guess! Technically it was an input error, but maybe in the next update the input could be automatically trimmed so we don't have situations like this again.

Thanks again for all the hard work with this site! It certainly makes keeping track of logsheets much easier.
