### ISSUE TITLE
Provide DMs the ability to categorize their logs? (Enhancement)

### ISSUE THREAD

**Issue by GrandPyromania** [Ariel-Thomas/adventurers-league-log#112]
Hey- I was wondering if DMs could get the ability to categorize DM logs then filter by the category. For example, if I categorized my DM logs as Tomb of Annihilation, then have the ability to show only that category, so that say, my DM rewards (which might have its own category) would not show up and clutter the page.

It would also make tracking things like Dedicated DM/other DM quests easier. Would also help DMs with multiple campaigns.

**Comment by Ariel-Thomas** [comment]
Added search function. We can revisit this later if needed.
