### ISSUE TITLE
Feature request: Consumable Tracking

### ISSUE THREAD

**Issue by sillvva** [Ariel-Thomas/adventurers-league-log#117]
It would be sweet to have the ability to have a similar method as adding magic items for adding consumables to a game log that would show up by the magic item list and can be marked as "used". And then have a filter to only show unused consumables.

**Comment by SANSd20** [comment]
Hmm, personally, i am not a very big fan of this idea. I feel that the log sheet should not be used for inventory management, and this feels like this is where this would be heading. 

Maybe I feel this way as there are other features that are needed more that haven't been added yet.

**Comment by Ariel-Thomas** [comment]
Maybe just a way of easily marking a magic item as used?
