### ISSUE TITLE
Notes <cr> formatting

### ISSUE THREAD

**Issue by 736dave** [Ariel-Thomas/adventurers-league-log#118]
I don't need a lot of formatting, but it would be nice for Notes to keep line-breaks.

e.g. 

**(not good)**

Mission 1: Beneath the Hills with Tyrannia, Bat, Ahmahgah, Lorcán, Ashton, Daryel, Eowyn. Other treasure: Add New Player Award (Ahmahgah, Lorcán, Daryel, Eowyn): Potion of Healing. Add (Daryel) another: Potion of Healing. Add (Ashton, ???): Vial of Alchemist’s Fire. Add (Ahmahgah): Blooddrinker the Bear story award. (Ahmahgah) Blooddrinker the Bear. Through care and patience, you now have a bear pet. She is, however, the size of a small housecat. She cannot attack, defend, distract, aid, or otherwise play any role in combat. She can be taught to do simple tricks if treated well and if you spend 20 down time days training her

versus:

**(good)**

Mission 1: Beneath the Hills with Tyrannia, Bat, Ahmahgah, Lorcán, Ashton, Daryel, Eowyn.

Other treasure:
Add New Player Award (Ahmahgah, Lorcán, Daryel, Eowyn): Potion of Healing.  
Add (Daryel) another: Potion of Healing.  
Add (Ashton): Vial of Alchemist’s Fire.  
Add (Ahmahgah): Blooddrinker the Bear story award.  

(Ahmahgah) Blooddrinker the Bear. Through care and patience, you now have a bear pet. She is, however, the size of a small housecat. She cannot attack, defend, distract, aid, or otherwise play any role in combat. She can be taught to do simple tricks if treated well and if you spend 20 down time days training her

**Comment by Ariel-Thomas** [comment]
Probably the thing we really need to do is have a separate notes section that isn't in the table but does appear on the show page that allows for formatting. Magic item description text maybe should allow for formatting as well.

@trezy

**Comment by trezy** [comment]
@Ariel-Thomas: Would you be opposed to allowing users to put Markdown into Notes fields like this? It should be a simple implementation, won’t require any database migrations, and allows users to have rich formatting like lists and such. If you’re up for that, I can look into implementing it this weekend.

**Comment by Ariel-Thomas** [comment]
Sure. Try to make use of a WYSIWYG editor like simplemde.

**Comment by trezy** [comment]
Oh man, I hadn't seen simplemde before. It looks awesome. We were about to write a custom one for @RollForGuild so you've just saved us a week of work. 🤣

**Comment by Ariel-Thomas** [comment]
I found a bug in the notes section where duplicate markdown areas were being created due to the functionality of the default SimpleMDE element selection. Making it more specific seems to have fixed that. Can you pull the new master down and confirm it's still working as expected for you before I push?

**Comment by trezy** [comment]
@Ariel-Thomas Yup, it all looks good. Good catch on that, btw. 😉

**Comment by Ariel-Thomas** [comment]
I've fixed the tests and added handling for the print version of the characters (it just strips markdown for now).

I've condensed the notes field on the tables a bit more. (similar to how it was before, but without the Notes header) I think it keeps from sacrificing useable real estate that way.

**Comment by trezy** [comment]
Awesome. I'll pull it down this evening and take another look. 😎

**Comment by trezy** [comment]
@Ariel-Thomas Since we've launched the Markdown updates, we can probably close this issue.
