### ISSUE TITLE
Eek - Lost Campaign

### ISSUE THREAD

**Issue by 736dave** [Ariel-Thomas/adventurers-league-log#119]
Hi Ariel-Thomas,
I had started a new campaign and was getting number of players and a couple of DM's to join it.
Today, I went to check on it and found it GONE!  please help!

Campaign: "Faerûn Vancouver"
Is is possible another DM removed me? 
I tried re-joining using my last good token and got "You are not authorized to perform this action."

**Comment by 736dave** [comment]
I am DCI 4317013876, if that helps

**Comment by Ariel-Thomas** [comment]
The system currently doesn't allow for DMs or Players to be removed. You would have had to remove yourself via using the delete button on the Campaigns page. Also, you would not be able to re-add yourself (nor could any DM join) since you didn't enable dm joining

I still show you attached to the campaign though.

Can you visit https://www.adventurersleaguelog.com/users/1675/campaigns/323 ?

**Comment by 736dave** [comment]
Oops sorry - that campaign (Faerûn Vancouver) was fine.  The missing one was "**Faerûn West Side**" - I had enabled DM joining and had a second DM already in.  (Maybe I could message him to see what he sees ... )

**Comment by 736dave** [comment]
The other DM was:
DM: Derry Oshust DCI: 2318829668

**Comment by 736dave** [comment]
I don't remember deleting it.  My guess is the third DM was attempting to 'remove and rejoin', not realizing that the trash can deletes the entire campaign rather than just removing his association ...

If so, does this mean it's lost forever? :-(

**Comment by Ariel-Thomas** [comment]
Yeah, that's some functionality I didn't think through when I added the ability for DMs to join campaigns. Let me see if I can recover it.

**Comment by Ariel-Thomas** [comment]
Did you have any log entries already made? If you can scare up a campaign relevant log entry's id (that number after log_entries/ in the url) or the old campaign id if you have an old link to the campaign (the number after campaigns/ in the url) I might be able to restore some of it.

**Comment by 736dave** [comment]
Yes!  This was still loaded on my home computer...
http://www.adventurersleaguelog.com/users/1675/campaigns/604

**Comment by Ariel-Thomas** [comment]
Alright, I've restored what I can.

**Comment by 736dave** [comment]
Thank you.  I will put the word out for folks to re-join :-)
You can mark this issue as resolved
