### ISSUE TITLE
DMQuest Adventure Title

### ISSUE THREAD

**Issue by TheSheDM** [Ariel-Thomas/adventurers-league-log#12]
DMQuests are likely to change often, so not suggesting adding the titles of each DMQuest to the list, but one title would do well as a generic entry for DMs to add DMQuest rewards under, then be able to assign those rewards to their character. I've been manually typing mine it, but if was already in there, possibly at the top of the list, it would be well used, I think. 

Example how I'm using it:  http://www.adventurersleaguelog.com/users/119/characters/744?q%5Bs%5D=date_played+desc

**Comment by brustmlj** [comment]
Ok

**Comment by Ariel-Thomas** [comment]
That link is giving me an empty character sheet.

**Comment by TheSheDM** [comment]
Whups! Sorry, I forgot and assigned my last DMs reward. I put one back on there for you to see.

**Comment by Ariel-Thomas** [comment]
Ah, I see it now. I may do this.

One thing I'm running into is that the list is starting to get really long, I may need to change it to a search feature or something similar in the future.

**Comment by TheSheDM** [comment]
Is making it a collapsible tree an option?  Expand it by Seasons:

Dungeon Master Quests
Lost Mines of Phandelver
Season 1
 - HC Horde of the Dragon Queen
 - HC The Rise of Tiamat
 - Modules
 - - DDEN-01 Horde of the DragonQueen
 - - DDEP-01 Corruption in Kryptgarden
 - - DDEX01-01 Defiance in Phlan  
Season 2 
 - HC Princes of the Apocalypse

etc. etc.  

 I don't know whats possible for you, I'm not a programmer, sorry if this isn't helpful

**Comment by Ariel-Thomas** [comment]
Yeah, could use collapsible trees or submenus. Currently we're just using html select. it may require a fair amount of additional JavaScript which may potentially be a little risky in terms of portability.
