### ISSUE TITLE
Good first issue

### ISSUE THREAD

**Issue by trezy** [Ariel-Thomas/adventurers-league-log#121]
Hey @Ariel-Thomas, I need to take work on something other than @RollForGuild for a little bit, and since I use this project like mad I figured I'd contribute a bit. Would you mind either pointing me to a good issue to start with, or tagging some issues with either the `help wanted` or `good first issue` tags? Also, a `CONTRIBUTING.md` file would be really helpful to make sure I don't step on your toes when making PRs. Thanks! 😁

**Comment by Ariel-Thomas** [comment]
Hey there. Having a bit of help would be great. I'll have a look this weekend and mark some stuff for you.
