### ISSUE TITLE
GM Log: Multiplier for Gold Value is incorrect

### ISSUE THREAD

**Issue by theloremaster** [Ariel-Thomas/adventurers-league-log#122]
Create a new Log Entry for 2 hours of play, and player Level 1
Verify that the XP, GP, and Downtime Days are accurate
Change the multiplier to 2. 
Verify that the XP, GP, and Downtime Days are accurate

FAIL, the initial calculation is correct, but increasing the multiplier changes the Gold value to Gold x4, not Gold x2. Higher multipliers do not change these values.

**Comment by Ariel-Thomas** [comment]
Good catch. I forgot GP was calculated from XP. Should be correct now.
