### ISSUE TITLE
Total/Unused quantities on DM logs are wrong

### ISSUE THREAD

**Issue by LordMailman** [Ariel-Thomas/adventurers-league-log#125]
After mid-June update, the "Total"/"Unused" quantities for XP, GP, DT, Renown, and Total Hours are wrong. They appear to be pulling only from the current page of the log, not the entire DM's log. The "Total" quantities seem to add together only from the logs displayed on that individual log page, while the "Unused" quantities are sometime larger than the page total?

**Comment by LordMailman** [comment]
[#125 - Example DMs Log page 1.pdf](https://github.com/Ariel-Thomas/adventurers-league-log/files/2106441/125.-.Example.DMs.Log.page.1.pdf)
[#125 - Example DMs Log page 2.pdf](https://github.com/Ariel-Thomas/adventurers-league-log/files/2106442/125.-.Example.DMs.Log.page.2.pdf)
For reference, the first two pages of my logs...

**Comment by Ariel-Thomas** [comment]
Yeah, I was trying to calculate it after the search results but it looks like that's boffed.
