### ISSUE TITLE
DM Sorting

### ISSUE THREAD

**Issue by Carmcritter** [Ariel-Thomas/adventurers-league-log#128]
I play under a lot of DM, is it possible to make the DM drop down menu(and probably the location drop down menu for some people) automatically alphabetical?

**Comment by Ariel-Thomas** [comment]
That's a good idea.

**Comment by Mahewa** [comment]
Somewhat along the same lines, I would love the ability to delete certain entries.  I have half filled in and blank ones in there.  I'm pretty sure I corrected the logs that originally had those, but there doesn't seem to be a way to get rid of those entries.

**Comment by Carmcritter** [comment]
There is a drop down at your email near the top that had DM Maintenance

**Comment by Mahewa** [comment]
Thanks!  I completely missed that.

I would echo your original request though.  Even after pruning, I have 57 DMs on that list and trying to remember when I would have first entered them on the site relative to the others is not an easy way to find them.
