### ISSUE TITLE
Locations lost?

### ISSUE THREAD

**Issue by ivey** [Ariel-Thomas/adventurers-league-log#135]
Hi, it seems like when the Location drop down went in, all my locations from previous entries were lost. I can probably reconstruct most of them, but maybe I missed a note about how to restore them?

**Comment by Ariel-Thomas** [comment]
I still see mine on the show page:
https://www.adventurersleaguelog.com/users/11/characters/11/character_log_entries/17437

If you click the manual entry button you should still see the location if
you're editing.

**Comment by ivey** [comment]
Yep, thank you. I was hoping it was that easy.
