### ISSUE TITLE
Help with search commands

### ISSUE THREAD

**Issue by GrandPyromania** [Ariel-Thomas/adventurers-league-log#141]
Hey- I really appreciate the ability to search, however is it possible to filter out certain entries or to get a better understanding of how to use the "advanced search" command? 

For example, I've titled my DM quests as "DM Quest S7" and would like to filter those specific ones out, but I can't necessarily use the "Adventure Title Contains" because I've DMed different seasons of content and for more than 1 group. 

Thanks!

**Comment by Ariel-Thomas** [comment]
> Hey- I really appreciate the ability to search, however is it possible to filter out certain entries or to get a better understanding of how to use the "advanced search" command?

Check out ransack's basic searching [here]([https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching]) for more options than just _cont.

>For example, I've titled my DM quests as "DM Quest S7" and would like to filter those specific ones out, but I can't necessarily use the "Adventure Title Contains" because I've DMed different seasons of content and for more than 1 group.

If you want to specifically ignore something go with adventure_title_not_cont like [so](https://www.adventurersleaguelog.com/users/11/dm_log_entries?utf8=%E2%9C%93&show_search=true&q=%7B%22adventure_title_not_cont%22%3D%3E%22DDEX%22%7D). If you want to ignore a bunch of somethings, you can do [this](https://www.adventurersleaguelog.com/users/11/dm_log_entries?utf8=%E2%9C%93&show_search=true&q=%7B%22adventure_title_not_cont_all%22%3D%3E%5B%22DDAL%22%2C+%22DDEX%22%5D%7D).
