### ISSUE TITLE
Create/Edit Log - Currently Broken on Mobile

### ISSUE THREAD

**Issue by feldoth** [Ariel-Thomas/adventurers-league-log#144]
The recent change to the text edit has caused a strange issue on mobile devices, when (what I assume is) the spellcheck functionality of the text editor kicks in mobile devices get stuck in a loop where the text highlighted in red is duplicated with every keypress, or touch event on the editor. This makes it impossible to create a new entry or edit an existing one, as the spellcheck has issues with words even as they are being typed.

Attaching a bluetooth keyboard fixes this issue, so it seems to be a problem with how touch input is handled. As a stopgap, disabling the spellcheck functionality of the editor would probably work - since pretty much all browsers have this built in anyway I doubt there's actually a need for it.

Picture of issue attached.

![screenshot_20180731-121012](https://user-images.githubusercontent.com/25411482/43472365-4402c154-94bb-11e8-8d3e-586a59672111.png)

**Comment by Ariel-Thomas** [comment]
Good catch.

**Comment by Ariel-Thomas** [comment]
Should be fixed now. Let me know.

**Comment by feldoth** [comment]
Hmm, no - there's no more red highlighting but the effect persists despite that. No change other than the highlighting is gone. Thanks for the quick action though.

**Comment by feldoth** [comment]
I have a OnePlus One, no special customizations - it uses the SwiftKey keyboard in case that makes a difference. I'm using Chrome for my browser.

**Comment by feldoth** [comment]
Correction: SwiftKey is installed but wasn't activated - the stock android keyboard was in use. I swapped to SwiftKey and the problem went away, so it appears to be at least somewhat related to the stock keyboard.

**Comment by Ariel-Thomas** [comment]
This looks like your problem?: https://youtu.be/meSMATEj_foe ?

**Comment by Ariel-Thomas** [comment]
We can maybe switch to EasyMDE. It's a fork of the original SimpleMDE.

**Comment by Ariel-Thomas** [comment]
Okay, done. Let me know if that fixes the problem.

**Comment by feldoth** [comment]
That did the trick, I can now type normally using either keyboard. Thanks a bunch!

**Comment by Ariel-Thomas** [comment]
Thanks for working with me to get this fixed.
