### ISSUE TITLE
Season 8 - Unlock Magic items

### ISSUE THREAD

**Issue by jabaran** [Ariel-Thomas/adventurers-league-log#148]
Since magic items are now unlocked in the adventure, change the ability to add a magic item from the adventure to add unlocked magic item for purchase.

**Comment by Ariel-Thomas** [comment]
Done

**Comment by Ariel-Thomas** [comment]
TODO: Add evergreen items.

**Comment by derammo** [comment]
About evergreen items:  do you need to add the concept of "Seasons" to track whether the adventure was played during the season date range when items are unlocked?

**Comment by Ariel-Thomas** [comment]
I decided to just set it up so you can manually enter an item.

**Comment by Ariel-Thomas** [comment]
Manual entry should work now.
