### ISSUE TITLE
Beta Missing Feature: Slow level conversion

### ISSUE THREAD

**Issue by willaien** [Ariel-Thomas/adventurers-league-log#153]
We currently have no way to do a "slow level" conversion/rounding down.  I'm aware that most players will gladly round up.

I'm fine with a manual workaround, which will involve doing the math myself and creating a new game entry for it with negative ACP, but wanted to bring it up.

**Comment by Ariel-Thomas** [comment]
I could theoretically add a user profile setting for this.

**Comment by willaien** [comment]
Wouldn't it need to be per-character? Regardless, the manual workaround works. (Tested)

**Comment by SANSd20** [comment]
It’s also per session.

**Comment by willaien** [comment]
For the general feature, yes. But this issue is with regards to the conversion process.
