### ISSUE TITLE
DM Log Entry: Renown

### ISSUE THREAD

**Issue by jabaran** [Ariel-Thomas/adventurers-league-log#158]
Renown appears to no longer be a thing in Season 8, so I suggest removing it from the input fields, or if this is for historical purposes making it read only.

**Comment by SANSd20** [comment]
Renown is no longer tied to factions, but to background.

**Comment by tjclayton** [comment]
This is incorrect. You can still be a faction agent and use renown. Also, if it is used for background it still needs to be tracked.

From the AL DMG 8.1:

> Awarding Renown: Characters earn one renown for every four advancement checkpoints they earn.

**Comment by jabaran** [comment]
Got it, missed that. Based on the discussions on FB it sounded like it was removed I didn't see it in the ALPG. Thanks!
