### ISSUE TITLE
no way to go back after the Print screen

### ISSUE THREAD

**Issue by RedLucidity** [Ariel-Thomas/adventurers-league-log#16]
I'm using Safari on a Mac. 
After selecting the print option the logs show for characters. (Looks Awesome!) 
But when I want to go back to the character there is not a back button or link to select to go back. If I hit the back page on the browser is takes me out of the site instead of to the main screen or the character who's  log I was looking at.

**Comment by Ariel-Thomas** [comment]
I'm mildly confused about this issue. Does Safari treat the back button differently than most browsers?

**Comment by Ariel-Thomas** [comment]
I've made the print buttons open in a new tab. We'll see how people feel about that and revert if there's an issue.
