### ISSUE TITLE
Bug: Traded items not being removed from item list

### ISSUE THREAD

**Issue by willaien** [Ariel-Thomas/adventurers-league-log#166]
After the conversion, items that were traded long ago have shown back up.

**Comment by Ariel-Thomas** [comment]
I'll fix that tonight

**Comment by Jimminc** [comment]
Can you also add an option to "trade" for TP, for those of us with problematic items?  Or please advise a way to remove those items?

**Comment by Ariel-Thomas** [comment]
> Can you also add an option to "trade" for TP, for those of us with problematic items? Or please advise a way to remove those items?

Since it has to be spent immediately, I would assume you would just do a normal trade log, except you put the new item as what you're trading for?

**Comment by Ariel-Thomas** [comment]
Bug should be fixed.
