### ISSUE TITLE
Missing hours field on S8 DM logs

### ISSUE THREAD

**Issue by ivey** [Ariel-Thomas/adventurers-league-log#173]
I use the Total Hours field for dedicated DM tracking, and would like to keep using it (assuming that quest survives)

Could we keep the hours field visible on the new form?

**Comment by Ariel-Thomas** [comment]
I thought none of the DM quests for season 8 involved hours

**Comment by ivey** [comment]
It seems you’re right. I hadn’t seen the new quest sheet yet.

That’s a bummer, I was at my next 22 hours :/

Thanks!
