### ISSUE TITLE
Bug: XP Conversion -> Round Down and Slow Progression - no half points

### ISSUE THREAD

**Issue by mrseidel** [Ariel-Thomas/adventurers-league-log#177]
After converting my character over with only 100XP, I chose to round down and use slow progression.  As such, I should have 0.5 ACP, but I noticed that all of the ACP are integers and it just rounded down to 0.

**Comment by Ariel-Thomas** [comment]
Wait, what? When did fractional ACP become a thing?

**Comment by mrseidel** [comment]
https://dnd.wizards.com/articles/news/changes-dd-adventurers-league-rewards

Under the **Slow Progression** section:
.... _Do not round, but rather track half points._ ...

**Comment by mrseidel** [comment]
I'm not sure, I would assume so based on the wording on Page 4 of the ALPG_v8.2.pdf file and the website I linked to, it talks about ACP, TP, and DT in the halfing portion.  I can't find anything on Facebook to confirm this though.  Would be worth investigating further to confirm.

**Comment by SANSd20** [comment]
The DDAL_Rewards_Announcement.pdf that is in the players packet, does say that treasure checkpoints and downtime days are halved.

It also says that this is an option "Each time you play in an adventure." I don't know if they mean each session when it comes to the HB or not.

**Comment by SANSd20** [comment]
from the ALPG:

**_Slowed Progression._** You may slow your character’s advancement. If you do so, your character earns any **checkpoints, downtime and renown** at half the normal rate. You may opt in or out of this between sessions.

**Comment by mrseidel** [comment]
This works for the Checkpoints, but it is not functional for the downtime to track half points (haven't tested renown).

**Comment by Ariel-Thomas** [comment]
Dammit. Missed the renown / downtime thing
