### ISSUE TITLE
Button to change password not working.

### ISSUE THREAD

**Issue by son-of-Wildfire** [Ariel-Thomas/adventurers-league-log#184]
My account is ed.tostanoski@duke.edu  

I try to use your reset password email button, and get (see attached)
![password reset error](https://user-images.githubusercontent.com/43017403/45123968-94f16b00-b136-11e8-9411-3f46177be189.PNG)

Copying link and pasting it also fails.

Please help.

**Comment by Ariel-Thomas** [comment]
Hm...

**Comment by Ariel-Thomas** [comment]
I just successfully used your reset_password_token to log into your account. Can you try resetting the password and trying again?

**Comment by son-of-Wildfire** [comment]
Sorry, Ariel.  I tried again, and got the same thing (see attached).

Still not working.  Feel free to just change it to something, and I’ll change it.


Ed Tostanoski III
4927 Whitfield Rd
Durham, NC 27707
home (919)403-7014
cell (919)200-5963

**Comment by Ariel-Thomas** [comment]
Okay, I've sent you the stuff, but I still need some help so we can maybe diagnosis this. What OS / Browser are you using?

**Comment by Ariel-Thomas** [comment]
My logs seem to indicate no request was ever made (there's literally no password/edit request that's not mine) so I think things never got sent.

**Comment by son-of-Wildfire** [comment]
I guess it’s on my end.  Sorry I couldn’t help troubleshoot, but I got in when you changed it, and now have it written down. :}>

Thanks for the product.  I should be able to donate starting next month.


-          Ed

**Comment by patromain** [comment]
I had the same problem.
I found a work around by changing the https by http in the url and it solves the problem.

On the other hand one would have to correct the template of the email of reset password to send a link without http and not https.

**Comment by shawncoons** [comment]
I'm having the same problem trying to reset a password:

![capture](https://user-images.githubusercontent.com/44980181/48366378-b7928980-e67b-11e8-8986-f2fd2d7aab81.PNG)

I tried the workaround changing https to http with no success.

**Comment by devnuhl** [comment]
I found the problem with this a while ago. Looking at submitting a PR for it right now.

**Comment by son-of-Wildfire** [comment]
Thanks, Chris.  That was a while ago.

Have a great weekend.


-          Ed

**Comment by devnuhl** [comment]
> Thanks, Chris. That was a while ago. Have a great weekend. - Ed 

It is still an issue with the site, though, and my edit was missing from the version of the comment you replied to about interim fixes. My PR was just submitted as well. Hopefully @Ariel-Thomas is alright and things might start getting merged. 

I'm off to look for more things I might be able to fix in the open issues list.
