### ISSUE TITLE
Pre-S8 Magic Items showing as Unlocked when added Post-S8

### ISSUE THREAD

**Issue by Menziesii** [Ariel-Thomas/adventurers-league-log#185]
[Character Sheet in question](https://www.adventurersleaguelog.com/users/8502/characters/24892)

[Adventure w/MI](https://www.adventurersleaguelog.com/users/8502/characters/24892/character_log_entries/245925)

I was bringing a character sheet up to date which included adding a magic item that had been gained before Season 8 went into effect. The magic item is showing up as "Unlocked" as if they were gained under the Season 8 system. This is occurring on two low leveled characters.

I cannot figure out how to show that it is not an unlock.

**Comment by Ariel-Thomas** [comment]
I don't understand, I see it on the sheet as purchased?

**Comment by Menziesii** [comment]
Well, I'm not sure quite what happened but the magic items are now displaying properly. Sorry!

Thank you so much for your time!
