### ISSUE TITLE
Fractional Downtime Days and Renown

### ISSUE THREAD

**Issue by SabreRunner** [Ariel-Thomas/adventurers-league-log#186]
Since 5 downtime days is gained for every 2 ACPs and 1 renown for every 4, players are allowed to track fractional progression on that front.
Can ALL allow that, please? Currently, it warns that they must be a whole number.

**Comment by SANSd20** [comment]
Yes please.

**Comment by rexmaxus** [comment]
I think that DTD and Renown should be handled like gold is handled. Auto update as the proper amount of ACP is earne, but still have a field for adjustments
