### ISSUE TITLE
Display Adventure Selection Better

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#19]
Suggestions go here.

**Comment by kenibrewer** [comment]
I have a group of 5-6 friends I've introduced to this site, and Adventure Selection is the thing they talk about as the most annoying. Here's how I would recommend fixing it. 

Selection Box 1: Downtime, Tyranny of Dragons, Elemental Evil, Rage of Demons, Curse of Strahd, Storm King's Thunder, Convention Created Content

Selection Box 2: Auto-populated with the specific options based on the what you select in box 1. 

If you are entering a new DM Log, there should be the additional option DM Quest in Box 1, which then fills Box 2 with the names of the different DM Quests.

**Comment by Ariel-Thomas** [comment]
Hrm. That's not a bad idea. I was leaning towards just a searchable list where you could input the first few characters and it would offer suggestions.

Can you explain what the problem you're hearing from them is specifically? What sort of devices are they using? Is it just that they find it hard to scroll down and select the right option?

**Comment by kenibrewer** [comment]
The auto-fill with suggestions option sounds like a good solution too.

We use all kinds of devices and we all have the same complaint. It's really annoying to have to take 30 seconds to scroll past all the content that has ever been published, before we get to the season 5 content that we're all playing right now.

**Comment by Ariel-Thomas** [comment]
Moved to autocomplete. Let me know how it works out.
