### ISSUE TITLE
Toggle per Campaign for whether to start by including or excluding everyone

### ISSUE THREAD

**Issue by SabreRunner** [Ariel-Thomas/adventurers-league-log#190]
I thought about starting a Campaign on ALL for organizing all the AL league DMs in my region. So, lots of DMs and lots of players. I would rather have to select which players to include in a new log than to exclude almost all of them.

**Comment by Ariel-Thomas** [comment]
This really isn't the intended use for the Campaign Log feature. I'm not necessarily opposed if someone wants to work on it and submit a pull request, but I will not.
