### ISSUE TITLE
My account does not work anymore

### ISSUE THREAD

**Issue by patromain** [Ariel-Thomas/adventurers-league-log#191]
Hi

I dont't arrive to log in my account.
My user is bourgade.romainATgmail.com.

Thanks
Romain

**Comment by Ariel-Thomas** [comment]
I don't have any users in the database with that name. It seems likely it was either a different email address or someone with access to your account deleted it.

**Comment by patromain** [comment]
This is the problem my account has been deleted and it is not me that is
done that.

Le sam. 15 sept. 2018 à 18:03, Ariel Thomas <notifications@github.com> a
écrit :

**Comment by Ariel-Thomas** [comment]
I can maybe help you, but it will be messy. Do you know what your old user id was? Like when you look at a link from your old account you should have www.adventurersleaguelog.com/users/##/

**Comment by patromain** [comment]
I don't have this information.
But the name of my personnage is "Titus Poulo" and "Maximus Theo".


Le sam. 15 sept. 2018 à 20:14, Ariel Thomas <notifications@github.com> a
écrit :

**Comment by Ariel-Thomas** [comment]
Alright, i did my best to set things back up for you, you should get an email to set up a new password shortly. Try not to let people have unfettered access to devices you save passwords on.
