### ISSUE TITLE
my account is busted.

### ISSUE THREAD

**Issue by shirogamer9** [Ariel-Thomas/adventurers-league-log#193]
everytime i try to log into my account i get a screen that says that "something has gone wrong with the app. if i am the owner check the logs"

i cant get past this when i log in. please help?

**Comment by Ariel-Thomas** [comment]
What email address are you using?

**Comment by shirogamer9** [comment]
rpgrlgamer@live.com

**Comment by Ariel-Thomas** [comment]
Ah, I see. You gave yourself negative XP.

**Comment by Ariel-Thomas** [comment]
Looks like Tanya Mayhem lived up to her name.

Should be fixed.

**Comment by shirogamer9** [comment]
Ha XD, Thank you so much!
