### ISSUE TITLE
State of the Tests

### ISSUE THREAD

**Issue by whazzmaster** [Ariel-Thomas/adventurers-league-log#194]
I'm just checking in to see what the state of the tests should be at the tip of master. I forked the repo, successfully (I think!) setup everything and when I run `bundle exec rake spec` I get the following results:

![failures](https://user-images.githubusercontent.com/102357/45790296-bb8cc700-bc49-11e8-9fe6-b3d000689b6e.png)

Is this expected? I noticed when the #165 merged it had CI failures so I wasn't positive that I setup things wrong. 

If these failures are known and expected as of right now, I'm happy to invest some time fixing them, but I didn't want to go down that road if they're _unexpected_ and I just missed a setup step.

**Comment by Ariel-Thomas** [comment]
Yeah, I was really uncertain about what things should look like for season 8 and I was trying to get the work done quickly so a lot of my tests fell behind. Fixing them is fairly high up on my todo list.
