### ISSUE TITLE
Missing AL Season 8 from Adventure Title

### ISSUE THREAD

**Issue by xcelsior-al** [Ariel-Thomas/adventurers-league-log#197]
Minor issue: there's no reference to Waterdeep: Dragon Heist or Waterdeep: Dungeon of the Mad Mage when entering the title.

**Comment by mortalis7** [comment]
Yes or any of the other session 8 adventures that so far have been released.

**Comment by thejohnnathan** [comment]
Just going to bump this since we're well into season 8 and last issue on this topic was Sep 20 2018 and it is not May 2019. Just need a two new inputs added to the Adventure Title dropdown for W:DH and W:MM. Thanks, loving this site.
