### ISSUE TITLE
Enhancement Requests 2

### ISSUE THREAD

**Issue by brustmlj** [Ariel-Thomas/adventurers-league-log#2]
A few more Ideas for Character Sheet
Season Origin Field
Background Field
Lifestyle Field
Calculate Faction Rank from logs renown and special missions

In general I think it would be better for the default sort to be based on the date of the character and the DM logs.  I know there is a sort column but this does not appear to be sticky.

DM Logs.  Filter for unused logs

**Comment by Ariel-Thomas** [comment]
Split into distinct parts
