### ISSUE TITLE
Incorrect TCP Total

### ISSUE THREAD

**Issue by tjclayton** [Ariel-Thomas/adventurers-league-log#204]
The character has 8 TCP, but the total lists 4 on the character page. See screenshot.

<img width="275" alt="incorrect tcp" src="https://user-images.githubusercontent.com/21241858/47053555-88bbed00-d17b-11e8-872e-f1856586d919.png">

**Comment by Ariel-Thomas** [comment]
Looks like you didn't set the Tier for the 4 hour one.

**Comment by tjclayton** [comment]
Thanks. That did the trick. Sorry for the false alarm.
