### ISSUE TITLE
enhancement: submit adventure code & title

### ISSUE THREAD

**Issue by ildesenesence** [Ariel-Thomas/adventurers-league-log#209]
Requesting the option to allow users to enter adventure code, hours & title to persist through their instance & generate a ticket for the admin to approve and add to the Big List of Adventures

**Comment by Ariel-Thomas** [comment]
Yeah, user maintained adventure listings probably make the most sense. They changed the PDF layout of the Content Catalog at the start of season 8 and it's broken my existing parser.

**Comment by SANSd20** [comment]
> Requesting the option to allow users to enter adventure code, hours & title to persist through their instance & generate a ticket for the admin to approve and add to the Big List of Adventures

I like the idea of it generating a ticket for the admin. If there is an error with the any part of it, the admin should be able to make changes and send those changes back upstream.
