### ISSUE TITLE
Lost Mine of Phandelver is listed twice

### ISSUE THREAD

**Issue by Maia-Everett** [Ariel-Thomas/adventurers-league-log#214]
The Lost Mine of Phandelver adventure is listed twice: once as DDHC-LMoP and once as DDHC-LMOP.

I recommend retaining DDHC-LMOP, as that is the official spelling in the AL Content Catalogue, and removing DDHC-LMoP.

**Comment by Ariel-Thomas** [comment]
Fixed in #228, thank you.
