### ISSUE TITLE
Unable to recover password

### ISSUE THREAD

**Issue by Greglando** [Ariel-Thomas/adventurers-league-log#218]
Hello everybody.

After formatting my PC, I was unable to recover my Account Password.
I recive the email to change it, but when I click on the link to "Change my password" the connection goes timeout after a while.

I tried to contact you with FB Messenger, but nobody answered, so I had to sign in with Gith Hub.

Please help me.

Best regards, 
Giovanni.

**Comment by kinghskac** [comment]
I too am having the same issue.

**Comment by devnuhl** [comment]
This is a duplicate of #184 and can be easily resolved if you simply add "www." before https://adventurersleaguelog.com.

There is currently a PR to solve this but the above will work anytime you need to change your password until that is merged into the code.
