### ISSUE TITLE
Add Donation Option

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#22]
Website's doing pretty well, which is good but that means more overhead. Going to have to upgrade my hosting plan, may become more costly if I implement game sessions with mail involved.

If a small handful of users would give small monthly donations, it would help offset the cost. Leaning towards a Patreon, mostly because I like the design and it's pretty transparent. PayPal would be an option as well. Thoughts?

**Comment by TheSheDM** [comment]
I'd certainly throw a few bucks your way.  I'd definitely suggest offering the option to do both one-time donations and subscriptions.  I prefer paypal, but a lot of folks do like Patreon - though I feel patreon tends to foster an environment of entitlement - "We're paying monthly, do more things for us" sort of attitude.

**Comment by Ariel-Thomas** [comment]
Settled on just using paypal.
