### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by sillvva** [Ariel-Thomas/adventurers-league-log#220]
I'm getting the following error when attempting to access the website.

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by Ariel-Thomas** [comment]
Has anyone else experienced this? I think the issue was with the server itself. Let's try and document future occurrences so I can track it down.
