### ISSUE TITLE
D&D adventurer's league log leveling up

### ISSUE THREAD

**Issue by The1CelticTiger** [Ariel-Thomas/adventurers-league-log#221]
I have 33 ACP but my online adventurer's league log says I'm level 6, is this a website error?

**Comment by SANSd20** [comment]
No. It is not. Tier 1 is 4 ACP each level. So that would be 20 to lvl 5. Once you hit that lvl (tier 2), it is 8 ACP to lvl. So you should be level 6 with 5 APCs.

**Comment by The1CelticTiger** [comment]
So 3 more ACPs will get me to level 7?

________________________________

**Comment by sillvva** [comment]
You don't start at level 0.
Level 2 = 4 ACP
Level 3 = 8 ACP
Level 4 = 12 ACP
Level 5 = 16 ACP
Level 6 = 24 ACP
Level 7 = 32 ACP

Mine is adding up correctly on the website. Are you sure you did your math correctly?

**Comment by SANSd20** [comment]
When you are right, you are right.

**Comment by The1CelticTiger** [comment]
I did my math correctly but the automated-leveling up website won't make it level 7 even though I'm level 33 on the site

________________________________

**Comment by derammo** [comment]
can you make  your log public and provide a link, so we can see?

**Comment by derammo** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/817160/54706348-1168fb80-4b15-11e9-8208-94f04a5e319e.png">

**Comment by The1CelticTiger** [comment]
It is listed as visible


________________________________

**Comment by The1CelticTiger** [comment]
It is listed as visible
https://www.adventurersleaguelog.com/users/10214/dm_log_entries

________________________________

**Comment by The1CelticTiger** [comment]
[cid:1d18466f-5c71-4ea7-acdc-ed56624aa158]

________________________________

**Comment by derammo** [comment]
Did you notice that the first of your DM rewards (worth 3 ACP) isn't listed as being awarded to your character?   That would put him at 30 ACP.   I think there is something screwy... it says it isn't awarded but also you don't have the ACP available.   I would try recreating that one DM reward record and then re-awarding it to see if you can fix that.

**Comment by The1CelticTiger** [comment]
Yep that fixed it, thanks man 😄

________________________________

**Comment by derammo** [comment]
cool beans, can you close the issue then?

**Comment by The1CelticTiger** [comment]
How do you do that?

________________________________

**Comment by derammo** [comment]
as the owner of this item, you should see the following "Close Issue" button at the bottom end of this conversation:

![image](https://user-images.githubusercontent.com/817160/54858645-7458bf00-4cdc-11e9-9f5e-c487b838a171.png)


Just follow the web link to the issue on github (web browser) and click the button (you need to be logged in.)

**Comment by Ariel-Thomas** [comment]
Thanks for providing support in my absence.
