### ISSUE TITLE
Adding Exp seems to advance too quickly - Halls of Heroes

### ISSUE THREAD

**Issue by 736dave** [Ariel-Thomas/adventurers-league-log#229]
One of our players: Put in a 9000 point module on a character 3ACP from LV 11 and it bumped him to LV 13... 

I tried this with (with NuÜg): adding 30,000 exp on a character 1 ACP from level 16 and he jumped straight to 17.  Changing character preferences to "Slow" "Round Down" worked better, but I am not sure if that is what is intended.  

Does this make sense?

Heads-up: Our group is switching from AL8/9 to Halls of Heroes (like AL7), i.e. switching back to exp/gold to better align with the Players Handbook.

Thanks

**Comment by 736dave** [comment]
I think my group is OK with either ACP or EXP (although I shouldn't waffle on this or I will T them off :-). We just want to get rid of the 'gold-as-a-salary' and the whole TCP/Tier/Table/Evergreen/... confusion ...

**Comment by derammo** [comment]
This site implements Adventurers League rules.   As such, XP is applied before ACP, essentially applying it before "conversion" to Season 8 rules.   Since it is illegal to apply any more XP later, it is not a problem.

**Comment by 736dave** [comment]
That explains the math, and makes total sense. Thanks. 

As we go back to EXP only, I will be sure to advise my players to not mix the two, and especially not to add Exp after adding ACP.

**Comment by Ariel-Thomas** [comment]
Sorry, I don't think the ability to add XP after ACP will be implemented. (though I'm not totally opposed if someone wants to do the dev work.)

Thank you for the report, though.
