### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by kimdvm** [Ariel-Thomas/adventurers-league-log#231]
I'm trying to reset my password.  I keep getting ERR_CONNECTION_TIMED_OUT message.  I tried several browsers and devices with no luck.

**Comment by devnuhl** [comment]
Duplicate of #184 
Work around is there. ([quick link](https://github.com/Ariel-Thomas/adventurers-league-log/issues/184#issuecomment-489213851))

**Comment by kimdvm** [comment]
Thank you.

**Comment by Ariel-Thomas** [comment]
Thanks for the report.

Fixed in PR #226
