### ISSUE TITLE
Suggestion: Multi-tier parties

### ISSUE THREAD

**Issue by SANSd20** [Ariel-Thomas/adventurers-league-log#233]
First off, glad you're back, Ariel.

What are the chances for those DMs running a hardback with multi-tier groups being able to have one overall log entry and some type of option to add entries for users for different tiers. Something akin to how we add different magic items. 

**How I envision this:**

The first and default entry is what everyone would normally use, but tier and characters would be moved to a seperate group next to each other.  A button labeled "Add Tier" or " Multi-tier" would be added to the bottom. For those running a single tier game, the only different they would see now is that the tier selection and a new button has been added.

For those you are running multi-tier groups, once we click on the "Add Tier" or " Multi-tier" button, we get another tier and character grouping. It would be nice if the characters/tier that was already selected in the 1st group where crossed/greyed out here.

_**EDIT (20190809t1123 -500)**: With the proposed Season 9 changes, this might be a moot point._

**Comment by SANSd20** [comment]
With the proposed Season 9 changes, this is a moot point.

**Comment by Ariel-Thomas** [comment]
:+1:
