### ISSUE TITLE
Date Played (really Date DMed) not showing on DM log list

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#24]
Not sure if this is related, but my DM logs don't show a date played anymore? Makes it confusing trying to figure out which event the DM log occurred at - important for tallying up events that occurred before or after a certain date.   

![20160823_102003](https://cloud.githubusercontent.com/assets/21070243/17902248/673bddfe-691b-11e6-91b1-05d49b6d18c8.png)

As per @TheSheDM

**Comment by Ariel-Thomas** [comment]
Ah. The problem was not quite what I thought. The DM log screen now separates Date DMed from Date Assigned (/Played). 

![screenshot from 2016-08-23 13-58-01](https://cloud.githubusercontent.com/assets/1067571/17905762/e0b78cbe-6939-11e6-9853-873ae54b1095.png)

I assume the issue you're having is that you use a separate character to track unassigned dm log entries and that's showing blanks. What we really need is a filter on the DM page to show unassigned log entries.

For a stopgap you should be able to get all your unassigned logs (assuming they're assigned to the  character you have displayed: http://www.adventurersleaguelog.com/users/11/dm_log_entries?q%5Bcharacter_id_eq%5D=127

**Comment by Ariel-Thomas** [comment]
The way I intend it to function will be more like: http://localhost:3000/users/119/dm_log_entries?q%5Bcharacter_id_null%5D=1

**Comment by TheSheDM** [comment]
Creating the "Not Assigned" character was the only way I could figure out to look at DM rewards that I didn't want/have assigned to my main character.  Right now if I look at the DM Log Entries and try to sort by character rewards, any logs not assigned to a character stay where they are, mixed in the list.
I have two right now (I took them off of "Not Assigned")
2016-06-08 17:51	Dungeon Master Quests
2016-07-27 21:08	Dungeon Master Quest

But if I sort by Character Rewarded, 2016-06-08 17:51 shows up on Page 2, and 2016-07-27 21:08 shows up on Page 3.  

.

**Comment by Ariel-Thomas** [comment]
Hrm, added a new issue for sorting by character (#25)

The expectation at this point is that you'll add Date Played to your dm logs to give you an ordering for when you assigned DM logs. (which I know you've got like 30 to go through... I guess I could try to set date_played to the same as date_dmed manually for all the currently existing entries if that would help.)
