### ISSUE TITLE
Characters without extra ACP are given a level

### ISSUE THREAD

**Issue by Maia-Everett** [Ariel-Thomas/adventurers-league-log#241]
All my characters with exactly as much ACP as needed to gain their level, and without any extra ACP progress towards the next level, were given a level. This is wrong, and furthermore I see no option to refuse this level.

**Comment by Ariel-Thomas** [comment]
You can set this on a per character basis via editing the character and
setting the rounding for conversion.

**Comment by Ariel-Thomas** [comment]
From the conversion guide:

> All advancement checkpoints are removed and you gain a level. As per Season 9 ALPG, this level can be declined.

By default your existent characters all gain a level regardless of how close they are to their next level, the number of ACP you have for your next level is irrelevant. The option to round down in conversion is there for those that want to decline this level.
