### ISSUE TITLE
DM Rewards - Date Assigned not bringing up current date/time

### ISSUE THREAD

**Issue by jestergi** [Ariel-Thomas/adventurers-league-log#242]
Since the work being done this weekend to prepare for Season 9 the **Date Assigned** function for the DM Rewards isn't populating any data. Clicking in the field is only bringing up previously entered info, but not auto-filling the current date/time. Given that many of us could be applying a great deal of rewards in the next few days I just wanted to bring it up in case it was a simple fix.

To be clear, this is when applying a DM reward with the Season 8 format.

**Comment by Ariel-Thomas** [comment]
Ah, I see the problem. This should be an easy fix.

**Comment by Ariel-Thomas** [comment]
Should be fixed now.
