### ISSUE TITLE
Possible level calculation error

### ISSUE THREAD

**Issue by SANSd20** [Ariel-Thomas/adventurers-league-log#243]
Looking over one of my charaters, it seems to have an extra level that I can't account for. I have "ACP to Milestone Rounding" set to down, but it is still showing me at lvl 3, when she should be lvl 2. She has not been played since before season 8 started.

https://www.adventurersleaguelog.com/users/549/characters/2422

**Comment by SANSd20** [comment]
To add to this, I see 500xp from DM rewards, and then 275xp, for a total of 775. She should have no ACPs so she should be lvl 2, not three as it is reporting.

**Comment by derammo** [comment]
it was probably rounded up when converting XP to ACP at season 8 start

check the character specific (not global) setting XP to ACP conversion it rounds up by default

**Comment by SANSd20** [comment]
That was it! i forgot about being able to round the XP up, so, i guess she really is lvl 3, thanks!

**Comment by Ariel-Thomas** [comment]
I know this issue got resolved without me, but I just wanted to say that it's great that we have something of a little community in the issues tracker here who can help one another out even without me.
