### ISSUE TITLE
Add DDAL09-03 Liar’s Night

### ISSUE THREAD

**Issue by Malacastre** [Ariel-Thomas/adventurers-league-log#251]
Please add

DDAL09-03 Liar’s Night

To the adventures list.

Thanks!

**Comment by psudopixel** [comment]
this also tracks back to updating the content catalog to 9.01 in #232

**Comment by SANSd20** [comment]
> Please add
> 
> DDAL09-03 Liar’s Night
> 
> To the adventures list.
> 
> Thanks!

That's the wrong code. _Liar's Night_ is DDEP09-03.
