### ISSUE TITLE
Option to not auto-calculate DTD

### ISSUE THREAD

**Issue by rexmaxus** [Ariel-Thomas/adventurers-league-log#253]
I am personally not a fan of my log sheets doing calculations for me. I must assume that others are in the same boat. Can we have an option to turn off all auto-calculations like the auto-DTD? Thank you.

**Comment by dalesd** [comment]
You're getting auto-calculated DTD?  
I'm not getting DT from DM rewards. I need to add another entry just for those.

**Comment by Ariel-Thomas** [comment]
I assumed DTD means Downtime Days?

If you edit the character you can set "Automagically Add Downtime" to "No"
