### ISSUE TITLE
Sort Characters by Level Option

### ISSUE THREAD

**Issue by Lotwook** [Ariel-Thomas/adventurers-league-log#266]
I recommend the level column have a clickable option in the character table like every other other column.

(indicating tier would also be helpful!)

**Comment by jestergi** [comment]
Seconded. Personally I've gotten around it by putting my level in my Class column, but it's just another thing I need to maintain as I level up.

![image](https://user-images.githubusercontent.com/33233883/85570708-950b7500-b601-11ea-8218-dc22c5ff7405.png)

**Comment by Ariel-Thomas** [comment]
Duplicates issue #208
