### ISSUE TITLE
1/3rd of entered DM's names are not showing up in Print view / Print copy

### ISSUE THREAD

**Issue by Hexfyre** [Ariel-Thomas/adventurers-league-log#27]
1/3rd of entered DM's names are not showing up in Print view / Print copy.  When I open the specific log, the DM's name is there.

**Comment by Ariel-Thomas** [comment]
Did this start after the last update?

Can you post a screen shot of what you mean?

**Comment by Hexfyre** [comment]
I just started using this site 2 days ago.  But it has happened on both of my characters.

![screenshot 2016-08-24 22 37 06](https://cloud.githubusercontent.com/assets/21227263/17954809/772b96c4-6a4b-11e6-9edf-e3421fc8281b.png)
![screenshot 2016-08-24 22 37 37](https://cloud.githubusercontent.com/assets/21227263/17954812/7b8183fa-6a4b-11e6-9c27-3f59d3268840.png)
![screenshot 2016-08-24 22 37 52](https://cloud.githubusercontent.com/assets/21227263/17954814/7ec29a54-6a4b-11e6-9abe-085f7802ba42.png)

**Comment by Ariel-Thomas** [comment]
Alright, I think this is fixed so I'm gonna close it. Please confirm when you get the chance.

**Comment by Hexfyre** [comment]
It looks great!  Thank you for the quick fix!
