### ISSUE TITLE
"Print Full" No Longer Fitting To Page When Printed

### ISSUE THREAD

**Issue by tjclayton** [Ariel-Thomas/adventurers-league-log#29]
Hello, 

Love the new changes. However, when I go to print the "Print Full" adventure log it no longer matches to the size of the US Letter pages anymore in landscape orientation. The very last Adventure Notes / Downtime Activites section for the 3rd entry extends onto a second page. I have tried playing with the scaling when printing, but then the other pages do not layout as expected. Is there anything you can do to tweak the layout?

I'm printing on a Mac to an Epson WF-4640 printer with the Epson driver.

Thanks for the great site.

Todd

**Comment by Ariel-Thomas** [comment]
Hrm... I hadn't even considered landscape orientation with my recent changes.

**Comment by Ariel-Thomas** [comment]
Pushing up a fix, let me know if it works for you.

**Comment by tjclayton** [comment]
Works great now. Thanks very much.

Todd
