### ISSUE TITLE
Improve Magic Item Handling

### ISSUE THREAD

**Issue by brustmlj** [Ariel-Thomas/adventurers-league-log#3]
Character Logs there is no clear way to log a magic item trade.  Can add the new item but not remove the old item.

**Comment by Ariel-Thomas** [comment]
Magic item handling is a bit of a thorn. I never implemented anything because I wasn't sure how the functionality would work.

**Comment by TheSheDM** [comment]
Idea: Treat items sorta like DM logs?  Fields: Item Name, Rarity (drop-down box), Adventure Title (same list w/ manual entry option), Date Acquired, Description, Assign to Character.  A reminder saying that trades should be noted in the character's logsheet notes would be nice too. 

After its assigned to a character, the item appears listed below the character info, but above the logsheet.  When printing, the condensed log prints just the Item Name, Rarity, Date Acquired.  The expanded prints the whole thing.

**Comment by Ariel-Thomas** [comment]
Magic items will have: Item Name, Rarity, Notes (Could be used for description is desired). Addable via DM or Character log entry form.

Show page would also provide a link to the log entry with the date and adventure name as identifiers.

Add TradeLogEntry which allows for removing old items and adding new items.

Other management necessary?
