### ISSUE TITLE
Extremely Minor: "Print Full" Shows "Starting M Items"

### ISSUE THREAD

**Issue by tjclayton** [Ariel-Thomas/adventurers-league-log#30]
The is very minor, but I don't think that it is intended. The "Print Full" page shows "Starting M Items" instead of "Starting Magic Items" as I think is intended. The other magic item lines spell out "Magic".

This has no functional impact.

I tried including a screenshot.

![starting m items](https://cloud.githubusercontent.com/assets/21241858/17975992/a7b0f866-6ab9-11e6-87b3-c802836b96ea.png)

**Comment by Ariel-Thomas** [comment]
Ah, yeah. I meant to fix that. It was originally that way due to an earlier spacing issue that I have since fixed. My goal with the full sheet was to match logsheet pretty much precisely.

**Comment by Ariel-Thomas** [comment]
Fixed.

**Comment by tjclayton** [comment]
Thanks. Sorry for the silly bug report.
