### ISSUE TITLE
Additional Request if possible.

### ISSUE THREAD

**Issue by taki021** [Ariel-Thomas/adventurers-league-log#33]
Good Day Sir Developer,

I am thankful for the website you have created, it had helped me and some of my friends. We have thought of many ways how to make the website more reliable for us DMs and Players. I hope you could hear us out for this request if it can possibly be done. (Will try to be detailed as much as possible)

1. In the DMs log, there are some of the DMs that would like to have information of the participants in their game, to keep track who has been playing in their table. We want to request a part of the DMs Log information were we can input the participants of the game (a table format) with the players name, DCI, character used and faction of the character. so that player can link their game log to the DM log that they did participate in the game.
2. A part also in the DM Log to know who among the characters (players) got the magic items and others and what additional story awards they gained. It is good it can be written in the notes section, but we wanted it organize so that the format will be good.
3. In the Trade Log Entry, please also include name of player, the character of that player we traded the item to and DCI and also notes area.

So far this is the main concern. We still have more, but we will wait for your further updates. Hopefully we don't stress you out.

**Comment by Ariel-Thomas** [comment]
I've broken these issues into separate pieces. Please try not to post a separate issue for each request in the future.
