### ISSUE TITLE
Request: Do not make Logging a dropdown

### ISSUE THREAD

**Issue by tjclayton** [Ariel-Thomas/adventurers-league-log#34]
Hi, I wanted to put in a request for consideration for while you are designing the new Campaigns functionality. I know that space is a premium in the header, but the Campaign functionality may likely be less used than the character and DM logging (at least by me since my AL play is in a shop with a variable group and I don't have a need to track attendance in this fashion). The functionality I use in the site is now two clicks away when before it was one. I know that it isn't a big thing, but it is less convenient when switching across my multiple characters or going back and forth between characters and DM entries. Just something to think about. I know that the Campaign piece has been an open enhancement and is much more useful to others. I appreciate it. Thanks, Todd

**Comment by Ariel-Thomas** [comment]
Yeah, this is a problem I've been trying to solve. The big issue are tablets (sm sized) with < 970px widths which are too big to just collapse the top into a full on drop down but makes for really limited menu space.

Possible solutions:
- Only convert over to the log dropdown for sm sized screens
- Shorten the menu named (PC Logs, DM Logs) or (PC, DM) and shuffle links to this page / Facebook into About dropdown.

**Comment by Ariel-Thomas** [comment]
Another option might be to have an actual homepage what you go to on login with links to recently updated characters, campaigns and such.

**Comment by tjclayton** [comment]
Perhaps the solution depends on how many people will use the campaign functionality??? If the intention is for it to be a separate "area" of the site, maybe have a logs area where you can switch between logs and a campaign "area" where you can group in other things that might come into play for campaigns. I'm not sure that makes sense.

**Comment by Ariel-Thomas** [comment]
I'm sorry, I'm not entirely sure what you mean. Are you suggesting that a given user has particular "modes" they can set themselves into that allows for access to only particular parts of the site?

I think I'm liking the home page best at the moment. With a home page that includes the ability to go to a character, start a DM Log, or go to a campaign (assuming you're using those functionalities, some customization for various users might be necessary) we could probably cut down the steps down to getting to what most people need to one click.

i.e. Before if you wanted to add a DM Log you have to click on DM Logs, then Create DM Log, but this would let you do so by just hitting a Create DM Log button from the first page loaded.

**Comment by tjclayton** [comment]
Not modes, I guess. Something like this image. I'm not suggesting this specifically, but with this once I click on logs the character/DM log options both stay there and I can easily just click once to switch between them. I personally don't mind the initial click, but I find myself clicking between characters, between DM logs and between character and DM logs often. Maybe that is just me.

![sample](https://cloud.githubusercontent.com/assets/21241858/18167978/79e19b3a-7021-11e6-9492-5f1fcabed0e3.png)

**Comment by Ariel-Thomas** [comment]
Ah! I see. That's not a bad idea.

**Comment by Ariel-Thomas** [comment]
Also, nothing wrong with being picky. I sympathize.

**Comment by tjclayton** [comment]
I'm definitely not a UI or usability expert. So, please take this as a completely uneducated piece of feedback. It could make things much worse.

I have terrible memory which I probably why I need to switch back and forth so often... :)

**Comment by Ariel-Thomas** [comment]
I'm curious, what are you swapping back and forth to check?

**Comment by tjclayton** [comment]
I'm not sure why, but I tend to bulk update characters. So, I go back and forth between the logs and also switch over to the DM logs to see where to best apply experience or magic items.

**Comment by Ariel-Thomas** [comment]
Made a change so that the logs in the navbar only collapse on sm sized resolutions. Home page thing still up for consideration.

**Comment by tjclayton** [comment]
Thanks very much.
