### ISSUE TITLE
DM Log Issue: Hide Assigned/Character Rewarded Sort

### ISSUE THREAD

**Issue by tjclayton** [Ariel-Thomas/adventurers-league-log#38]
This worked before, but now when I go to my DM log and click the hide assigned button, it does not clear the entries assigned to characters. Similarly, sorting by character assigned does not work. Sorting on the other columns appears to work correctly. I tried this in both Firefox and Safari on a Mac.

I wasn't sure what other info to provide. I attached an animated GIF showing the behavior. If I can provide anything else, please let me know.

![char-assigned](https://cloud.githubusercontent.com/assets/21241858/18226597/57fc10e8-71db-11e6-8c17-cd4daddbfc9e.gif)

**Comment by Ariel-Thomas** [comment]
This is one of the best but reports I've ever received.

**Comment by Ariel-Thomas** [comment]
Fixed by #39

**Comment by tjclayton** [comment]
Works great now. Thanks very much.
