### ISSUE TITLE
Issue: Drop down boxes do not show current value

### ISSUE THREAD

**Issue by brustmlj** [Ariel-Thomas/adventurers-league-log#41]
Is there a way or a different widget that will show the current value of a drop down box in the edit window? When editing it is hard to tell when it has be set or when it has not.

Specifically field like DM on a character log and Character assigned on a DM log.  Non static drop downs.

**Comment by Ariel-Thomas** [comment]
>Is there a way or a different widget that will show the current value of a drop down box in the edit window? When editing it is hard to tell when it has be set or when it has not.

If there's a problem with these, it's not likely a general issue but something to do with how the models are set up.

> Specifically field like DM on a character log and Character assigned on a DM log. Non static drop downs.

Okay, I see that characters are coming up blank in the `Character to Apply Rewards` dropdown, but not the DM dropdown on the character log edit page... Any chance you have more specific info there?

**Comment by brustmlj** [comment]
For me DM dropdown is always blank on the edit.  I was working mostly on my character Brand and Stick.  Jackin was the DM and it always seemed blank even when previously assigned.

**Comment by kenibrewer** [comment]
This bug seems to have been fixed in the last update. Both the DM dropdown and the Character to Apply Rewards dropdown have the correct option filled in if they have been previously assigned.

**Comment by Ariel-Thomas** [comment]
Interesting, this must have been related to #47 in some way.
