### ISSUE TITLE
DM Log Entry Alignment Adjustment

### ISSUE THREAD

**Issue by taki021** [Ariel-Thomas/adventurers-league-log#43]
![snap 2016-10-08 at 02 07 46](https://cloud.githubusercontent.com/assets/19564707/19200582/60658034-8cfc-11e6-9e75-b955db674e2a.jpg)

Hi Developer,

Please see screenshot, please fix/adjust the alignment. All of my logs are showing like that.

Thank You.

**Comment by Ariel-Thomas** [comment]
Shoot. Stray tag.
