### ISSUE TITLE
Accessing DM Log Entry directly from Character Log

### ISSUE THREAD

**Issue by kenibrewer** [Ariel-Thomas/adventurers-league-log#44]
Currently, if I forget to include a Date Assigned on a DM Log entry when I assign it to a character. It is extremely challenging to go back and fix it. 

The problem is that there is no direct link to editing a DM log entry from a character's expanded log sheet. I would recommend replacing the red (DM LOG) unclickable button with a link to the DM log entry so it can be edited. 

![image](https://cloud.githubusercontent.com/assets/17461269/19622753/8b20e7d0-987f-11e6-8a85-e80f5f771716.png)

**Comment by Ariel-Thomas** [comment]
Good call

**Comment by kenibrewer** [comment]
Thanks! Both for making this change and the other two I requested. This change in particular took care of what was once my biggest frustration of using the site.
