### ISSUE TITLE
Additional Uploads for Players

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#5]
Would it be possible to upload pictures of certs received?
Would it be possible to upload signed logs like received at Fai Chen’s?

**Comment by Ariel-Thomas** [comment]
This seems like it should be folded into a new magic item handling system. 

There's a potential problem with file sizing. How big would be allowed as big enough for clarity?

**Comment by brustmlj** [comment]
I am not sure what sizing constraint you have.  Around a 100k would probably be good enough maybe less.  Not sure how well that scales.

**Comment by Ariel-Thomas** [comment]
You know, I just realized I haven't actually implemented any storage here. I think my original idea was to use AWS S3. Might be easiest to just do an image link like the character photo.
