### ISSUE TITLE
Printing Logs with DM entries missing information

### ISSUE THREAD

**Issue by Mahewa** [Ariel-Thomas/adventurers-league-log#50]
When I display DM entries and go to print the log, the DM entries only show the date.  This is true in condensed and full print versions.  They don't show the  adventure name or session number, which would be nice to have.  Since there's no need for the DM name and DCI, I think it would make sense if the top line showed, if possible,: adventure name - session # - Date DMd - Date assigned - DM REWARD (like the trade log designation).

**Comment by Ariel-Thomas** [comment]
I believe I removed the adventure name and session because I didn't want it to be confused with actual adventures that had been played. Might just add a tag before the adventure name to designate it as coming from DMing.

Will consider shuffling it like the trade log.

**Comment by Ariel-Thomas** [comment]
Actually, no. Something's wrong with it not displaying the adventure title and date. Definitely a bug.

**Comment by Ariel-Thomas** [comment]
Done
