### ISSUE TITLE
Track hours for Dedicated DM

### ISSUE THREAD

**Issue by rooneg** [Ariel-Thomas/adventurers-league-log#51]
It would be nice if it was possible to track the hours for each adventure and use that to calculate things like the Dedicated DM Quest.

**Comment by Ariel-Thomas** [comment]
Yeah, this is something on my todo list with the DM Quests stuff. I'm not entirely sure how to handle this, though. I'm thinking I may have a field where you can enter hours (not sure what to call the field) and maybe level with a button or checkbox to let you automatically fill relevant XP, GP, Downtime, and Renown for book adventures as well as tracking overall hours for quests.

**Comment by rooneg** [comment]
Yeah, you probably want to be able to default to the known right hours for DDAL/DDEX style adventures, and give a way to include it with hardcover sessions, keep a running total and then subtract from it when people add a Dedicated DM entry.

Might also want something similar for the various "I ran all the adventures" quests, although it might not be worth the effort if those aren't an every season kind of thing. Heck, Dedicated DM might not be worth the effort if it doesn't stay the same in the next set of quests.

**Comment by Ariel-Thomas** [comment]
Alright, working to implement something for this. 

Current plan for backfill is to start at August 26th, 2016 and to set most modules hours based on 5 downtime = 2 hours, with the exception of the 5 intro modules which will be 5 DT = 1 hour.

**Comment by kenibrewer** [comment]
There's a lot of complexity to counting hours for Dedicated DM. Some mods (like Convention Created Content) don't count. A direct downtime to hours conversion also wouldn't work for other reasons. When my adventure rewards (incl. downtime) are doubled by Quest of the Week, or Ethereal DM DM Quests, I usually enter the doubled rewards instead of creating a separate DM Quest entry. Would that cause difficulty with the Backfill?

**Comment by kenibrewer** [comment]
I still think a system for tracking Dedicated DM rewards would be useful. However, unless I am misunderstanding the meaning of "Backfill", I wouldn't automatic rules for data that people haven't entered themselves. 

Also, if you're looking for module runtimes you can find that and all the DM Rewards for all modules listed in the spreadsheet linked below. It might also be useful for future enhancements like automatically filling in the default reward values for a module and then checking a box for "Quest of the Week" to double the default values. 

https://docs.google.com/spreadsheets/d/1omoTExpdh7cdiq9NnfVpf6-CnAkGRbA-FMIiNaZXpvg/edit#gid=0

**Comment by rooneg** [comment]
It may be best to simply not backfill. Allow people to go back and tag
their own stuff with hours (if they aren't obvious, I mean you know what
hours they are for any DDEX or DDAL adventure) and associate those entries
with a Dedicated DM quest, but don't try to do it automatically.

**Comment by Ariel-Thomas** [comment]
Hrm, is there any reason at the moment to track hours for anything other than Dedicated DM? I'd prefer people not have to have exact adventure names to qualify for it so I'd just as soon make any hours entry part of the dedicated DM pool.

**Comment by Troacctid** [comment]
Odd-numbered sessions of hardcover adventures, I guess.

**Comment by Ariel-Thomas** [comment]
This is a thing now that exists. I didn't do any back patching.

**Comment by rooneg** [comment]
A few things to consider here: Now that hours are being used to calculate XP if we also want them to be usefully trackable for Dedicated DM there needs to be a way to exclude some adventures from that total. As of Season 5 quest rules (not sure about Season 6 for sure since it isn't out yet) only Hardcovers, DDAL and DDEX adventures count towards Dedicated DM. You can't count Epics or CCC. Right now I'm just not logging hours for epics, but that would mean calculating the XP by hand.

**Comment by Ariel-Thomas** [comment]
I'm getting the feeling I may need a list of checkboxes on the DM screen.

Current workflow for not calculating by hand though: New -> Enter Length and Level -> Uncheck Autocalc -> Set Level and Length to whatever.

**Comment by rooneg** [comment]
Yeah, it may also be useful to have a multiplier field, for the various "this quest doubles the rewards" sort of things you might want to apply.

**Comment by tjclayton** [comment]
Personally, I think this is trying to automate too much. I would keep it simpler with letting people just add the total. Every season things seem to change the calculations.

**Comment by Ariel-Thomas** [comment]
@tjclayton Could you clarify what you're referring to specifically?

**Comment by tjclayton** [comment]
Instead of default hours, having checkboxes to double the reward, trying to auto-calc, etc. just keep it being entered manually. Since it seems like this is mostly done, the feedback is probably moot at this point.

**Comment by Troacctid** [comment]
Maybe we could get a setting to have auto-calc turned off by default?

Also, it would be useful if the hours were displayed on the main page along with session, xp, gp, etc. so as to not have to click the thing to see them. (And while you're at it, maybe put in a column there for renown too?)

**Comment by rooneg** [comment]
Auto calc is on by default, create a new dm entry, add the hours and the party level and it fills in the rest.

**Comment by Troacctid** [comment]
I know it's turned on by default, would be nice to be able to have it turned off by default instead, though.

**Comment by rooneg** [comment]
Sorry, misread. I'm not clear why you'd want to turn it off by default. As of the 24th this is how XP for all adventures is supposed to work, the only time you don't want it is if you're backfilling some stuff or you're applying a multiplier, in which case you can either leave out the party level (for backfilling) or you can multiply after you've seen the default calc results.

**Comment by Troacctid** [comment]
Yeah, I'm backfilling, and I have multipliers on everything (minimum x2 from Ethereal DM). Also, I'm paranoid that I'll accidentally change one of the values and make it reset to the default.

**Comment by Ariel-Thomas** [comment]
I have a question on multipliers. Are the effective hours multiplied too? i.e. Would a 4 hour mod effectively be 8 hours for Dedicated DM?

**Comment by rooneg** [comment]
No, just XP/GP/Downtime.

**Comment by rooneg** [comment]
Although you should also keep in mind that we're operating on the assumption that it all keeps working the way it did for season 5, the DM Quests for season 6 won't be out till sometime next week, the rules could change out from under us.

**Comment by Ariel-Thomas** [comment]
Good point. I think I'm going to just sort of leave this alone for the moment until DM Quests for Season 6.

I'll add an enhancement to allow toggling auto-calc by default.
