### ISSUE TITLE
Problems with Making Profile Public

### ISSUE THREAD

**Issue by kenibrewer** [Ariel-Thomas/adventurers-league-log#54]
I checked the box in my profile settings to make my characters/logs public but I'm still having trouble accessing them without logging in. 

For example when I open an incognito window and navigate to the page where I expect to find one of my characters (http://www.adventurersleaguelog.com/users/505/characters/1461), I instead am redirected to the homepage and am asked to log in? 

Is there just a delay after checking the "Make Profile Public" page and when it takes effect? If so, perhaps it would be good to inform users of that.

**Comment by Ariel-Thomas** [comment]
There shouldn't be. I'll have a look tonight.

**Comment by kenibrewer** [comment]
I have confirmed this is a problem with more than one account. My friends who use the service also can't make their logs public.

**Comment by Ariel-Thomas** [comment]
Ah! It took me a bit, but I finally get it. 

I only ever intended that flag to toggle the DM Logs. I do like the idea of having a way to let people have a look at your characters, though. I will split the concepts into two different flags.

**Comment by kenibrewer** [comment]
Yes, it's much nicer to be able to give my DM a link to my logsheets instead of exporting it to a pdf for them.

**Comment by Ariel-Thomas** [comment]
Well, you can mark individual characters as public already (which seems to be working just fine).

**Comment by Ariel-Thomas** [comment]
Okay, this is done. Let me know if it's working like you expect now.

**Comment by kenibrewer** [comment]
This still doesn't seem to work properly. When I check the box for "Publicly Visible Characters" it doesn't stay checked when I save then refresh the page. It also doesn't make any of my characters visible that I haven't already marked as visible on an individual basis.

**Comment by Ariel-Thomas** [comment]
I tried restarting the server, that seems to be working proper now. Try again.
