### ISSUE TITLE
Adding Missing Modules

### ISSUE THREAD

**Issue by kenibrewer** [Ariel-Thomas/adventurers-league-log#56]
The following modules are incomplete and need to be entered into the system.

DDAL05-11	Forgotten Tradition
DDAL05-12	Bad Business in Parnast
DDAL05-13	Jarl Rising
DDAL05-14	Reeducation
DDAL05-15	Reeducation Part 2
DDAL05-16	Parnast Under Siege
DDAL05-17	Hartkiller's Horn
DDAL05-18	Eye of Xxiphu Part 1
DDAL05-19	Eye of Xxiphu Part 2

**Comment by Ariel-Thomas** [comment]
I'll add these tonight.

**Comment by kenibrewer** [comment]
There are also two modules whose names were changed. DDAL05-08 and DDAL05-09 have been renamed "Durlag's Tower" and "Durlag's Tomb" respectively

Not sure how comprehensive you want to be, but here is all the publicly released Convention Created Content, in case you would like to add that too:

CIC-01	The Vault of the Devourer
CORE1-1	A Scream in the Night
CORE1-2	A Cog in the Wheel
CORE1-3	A Hole in the World
CORE2-1	Tales of Good and Evil
CORE2-2	Songs of Law & Chaos
CORE2-3	Edicts of Neutrality
ELM1-1	The Sage of Cormathor
GHC-01	Tharaera Lost
GHC-02	Skulljaw Hill
GHC-03	Facing the Dark
HILL1-1	Arrival 
HILL1-2	Exodus
HILL1-3	Resurgance
HULB1-1	Hulburg Rebuilding
HULB1-2	Hulburg Burning
HULB1-3	Hulburg Rising
PHLAN1-1	Sepulture
PHLAN1-2	Enemy of my Enemy
PHLAN1-3	Subterfuge
UCON-01	Blood and Fog

And the one publicly-released (former) DDAO:

DDAL00-01	Window to the Past

If it would be helpful, I can add a comment here every month or so with the names of newly-released modules.

**Comment by Ariel-Thomas** [comment]
That would be nice, yeah. Now that I have moved to autofill and that seems to be working well I can more freely add stuff without clutter being an issue.

**Comment by kenibrewer** [comment]
Great. In that case I'll post periodically with the new modules.

**Comment by Ariel-Thomas** [comment]
Done. Make a new thread for new modules.
