### ISSUE TITLE
Allow multiple DMs to contribute to a campaign

### ISSUE THREAD

**Issue by jhempy** [Ariel-Thomas/adventurers-league-log#58]
Sometimes players rotate DM responsibilities in a campaign, or a substitute DM fills in when the regular DM is unavailable. Allowing multiple DMs to log their sessions' activity in a campaign attributes rewards to the right source and keeps better track of what actually happened.

**Comment by Ariel-Thomas** [comment]
Will go into the queue

**Comment by Ariel-Thomas** [comment]
So, conceptually here, we add a DM Join token that people can hook up to the campaign with that can be allowed / disallowed like the player join token.

I don't want to add admin controls anytime soon so this would potentially risk someone being a little terror. Could potentially make the token expire?

**Comment by jhempy** [comment]
I think this would work. I wouldn't bother with token expiration; if the
guest DM is being a jerk, he can be disallowed.
