### ISSUE TITLE
Additional Character Sheet Fields

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#6]
Add to Edit Character page:

Season Origin Field
Background Field
Lifestyle Field (with selectioins)
Calculate Faction Rank from logs renown and special missions (remove rank field from edit)

**Comment by Ariel-Thomas** [comment]
Done
> Season Origin Field
>Background Field
>Lifestyle Field (with selectioins)

TODO
> Calculate Faction Rank from logs renown and special missions (remove rank field from edit)

**Comment by Ariel-Thomas** [comment]
Drop Season Origin since it won't be relevant with the new Player's Guide.

**Comment by RedLucidity** [comment]
True the Season Origin is being dropped. But its being replaced with Source book options being used. For instance: Elemental Evil Players Guide and Players Handbook or Players Handbook & Sword Coast Adventures Guide. 
These options should be selectiable when creating or editing the Character info part of the Log. Also a Background field (and/or Custom fillable). The Lifestyle can change as a character adventures, but should be listed. 

Having a Story Origin log entry might be nice when creating the first log or the options could be part of the main part of creating a the character Log.
As an example this is the kind of detail I end up putting on all my new characters first log entry.

_### **Story Season:** Rage of Demons; PH, SCAG, RoD Backgrounds. **Race:** Human - Halurraan; **Class:** Wizard;  **Faction:** Harper; **Alignment:** Chaotic Good; 
**Skill Proficiencies:** Arcana, Investigation.;
**Equipment:** Dagger, Component pouch, Scholar's Pack, Spellbook

**Background:** Cormanthor Refugee; **Lifestyle:** poor; **Feature:** Shelter of the Elven Clergy **Language Proficiencies:** Elven **Tool Proficiencies:** One type of artisan's tools (Alchemists Tools) **Skill Proficiencies:** Nature, Survival;
**Equipment:** A two-person tent, artisan's tools (Alchemist's Tools), a holy symbol Rallathil, a set of traveler's clothes, a belt pouch, 5 gp

**Class Options:** ; **Cantrips:** 1) Light 2) Green Flame Blade, 3) Lighting Lure;
**Spellbook:** 1st level Spells: Detect Magic, Identify, Magic Missile, Shield, Sleep, Tasha's Hid. laughter; _

It might also be nice to be able to import or export the log via XML data. 

Thank you for making and hosting the AdventureLeagueLog its been an Extremely Huge Help to me in getting my DM logs all sorted and tracked!

**Comment by Ariel-Thomas** [comment]
Closing this for now. Please make another issue for further requests.
