### ISSUE TITLE
Printable DM Logs

### ISSUE THREAD

**Issue by Troacctid** [Ariel-Thomas/adventurers-league-log#61]
Would it be possible to print a PDF of the DM Logs like you can for characters? Currently you can do it on a per-character basis, but I'd like to be able to do it for all my DM rewards.

**Comment by Ariel-Thomas** [comment]
Done.

**Comment by Troacctid** [comment]
Thanks! But I notice it is missing some key information, namely the character the reward was assigned to (if any)! Could that possibly be added in?

**Comment by Ariel-Thomas** [comment]
Yeah, it's currently just mimicking the default. Needs Date DM'd and Character applied, then? Anything else?

**Comment by Troacctid** [comment]
I'd also include Date Assigned, Location DMed, and Missions. You can also just use the condensed sheet since the starting and total amounts are meaningless for DM rewards that are probably assigned to multiple different characters.
