### ISSUE TITLE
Parse AL Content Catalog for Its Sweet Secrets

### ISSUE THREAD

**Issue by kenibrewer** [Ariel-Thomas/adventurers-league-log#62]
The admins have released a content catalog listing all of the legal AL content and new/updated adventure codes for lots of things. They'll be updating it quarterly. 

This would be a good place to pull the names for all the existing adventures and the stuff coming in the new season. It also has the codes/titles for all of the Author Only modules and other limited content. 

http://www.dmsguild.com/product/208140/Adventurers-League-Content-Catalog

**Comment by Ariel-Thomas** [comment]
This might actually be parseable if they stay consistent on formating in the future.

**Comment by tjclayton** [comment]
Why try to parse a PDF when you can simply copy the tables (with their formatted) using Acrobat into Excel and save it as a CSV. Adding parsing seems like a lot of work for something updated for times a year and can be easily transferred to CSV.

**Comment by Ariel-Thomas** [comment]
Delicious secrets consumed.
