### ISSUE TITLE
Printing DM Logs results in error

### ISSUE THREAD

**Issue by rooneg** [Ariel-Thomas/adventurers-league-log#63]
When I try to print my DM logs I get an error screen that says to consult the application logs (presumably some sort of exception is getting thrown).

**Comment by Ariel-Thomas** [comment]
Hrm...  Okay, I think I found the source. It errors out if you didn't give one of your entries a date. Looks like this is a quick fix.

**Comment by rooneg** [comment]
That explains it. I've got a few entries preloaded that I'm planning to run but haven't scheduled yet.
