### ISSUE TITLE
Average Party Level Field is Misleading

### ISSUE THREAD

**Issue by rooneg** [Ariel-Thomas/adventurers-league-log#64]
The new Average Party Level field is a bit misleading, since for non-hardcover adventures you're supposed to use the level the adventure was optimized for, not the level the party was actually at. Not sure what the ideal wording is (only so much room on the page), but maybe switch the field lablel to Optimized Level when you've used one of the DDAL/DDEX autocompleted adventure names? Could even set it by default based on the adventure name.

**Comment by Ariel-Thomas** [comment]
Ugh, that's a lot of extra effort for very little return, but you're right that Avg Party Level isn't the best naming. Behind the scenes it's just Player Level. Maybe that would be fine.

**Comment by rooneg** [comment]
Yeah, "Player Level" is better, maybe with some explanatory mouse over text or something ;-)
