### ISSUE TITLE
Color Code or Add Indicator for Magic Item Rarity (Enhancement)

### ISSUE THREAD

**Issue by tjclayton** [Ariel-Thomas/adventurers-league-log#68]
It would be nice to be able to see the rarity of the magic item from the character main page without having to find the entry with that item (based upon what you assigned when you added the item). This helps when I'm trying to look through quickly to see what I have to trade for certain rarities. I'm sure that most people have better memories than I do and can recall off the top of their heads what they are, but my brain doesn't work that well. Thanks.

**Comment by Ariel-Thomas** [comment]
I think I'm going to go a slightly different route and have a separate Magic Items page that can be accessed via click a link on the Character page. That should meet your needs of being able to see all the items and their rarity easily. I guess I could still color code the lines, similar to what I do with the log entries if that's appealing.
