### ISSUE TITLE
Improve Character / DM Log Sorting

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#7]
In general I think it would be better for the default sort to be based on the date of the character and the DM logs. I know there is a sort column but this does not appear to be sticky.

**Comment by Ariel-Thomas** [comment]
The default sort is already based on the date.

What do you mean by sticky? That it doesn't maintain the next time you click on the character from the character selection page?

**Comment by brustmlj** [comment]
Actually I have seen the character data sort remain sticky.  I think the DM log sort is not.  When I come back to the DM page I have to sort the logs again.

 

Mike

**Comment by Ariel-Thomas** [comment]
You're right. DM Logs aren't default sorted by date. I'll fix that.

**Comment by Ariel-Thomas** [comment]
I've fixed the sorting issue and implemented stickiness in related actions. (new, edit, delete)
