### ISSUE TITLE
Publicly viewable?

### ISSUE THREAD

**Issue by Daedallus1978** [Ariel-Thomas/adventurers-league-log#70]
I see checkboxes for publicly viewable in various places, but i dont see anywhere to link to or search for characters that are not mine.

Is this future functionality?

**Comment by Ariel-Thomas** [comment]
Possibly, but the public viewable is about being able to give someone a
link to your character or dm log and them being able to see it

**Comment by Ariel-Thomas** [comment]
Did you have a particular sort of thing you wanted to search for?
