### ISSUE TITLE
Log in Issue

### ISSUE THREAD

**Issue by xanstin** [Ariel-Thomas/adventurers-league-log#74]
I tried to change my email and now it doesn't let either previous or current email work. I basically went to update password page, put in the new email and password saved and it kicked me out to login screen and nothing works. In addition all my character links are now broken to my public logs. I was user 418 if that helps.

**Comment by xanstin** [comment]
I was user 418 if that helps

**Comment by Ariel-Thomas** [comment]
Resetting your password not working?

**Comment by xanstin** [comment]
no i am putting in the old and new email and it says neither account is found.
"1 error prohibited this user from being saved:
Email not found"

Any old links to PC's or DM Log result in 
"The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."

I cant lie I am panicking a little bit....

**Comment by Ariel-Thomas** [comment]
Very informative.  I'll try to solve this tonight

**Comment by xanstin** [comment]
Do you need any info from me? I was user 418....if you can just roll back to fgxanstin email and the password before this that is fine. i can live with it over loosing my logs

**Comment by Ariel-Thomas** [comment]
I'm driving home from a convention.  Will probably be another hour

**Comment by xanstin** [comment]
Drive safe man. Thanks for the quick response... downgrading from full blown panic to concerned ;)

**Comment by Ariel-Thomas** [comment]
Worst case your use entry was deleted,  but your logs should be safe and we
just have to reattach them.

**Comment by Ariel-Thomas** [comment]
I'm going to need an email from you. If you don't feel comfortable posting it here, message me on Facebook here: https://www.facebook.com/AdventurersLeagueLog/

**Comment by xanstin** [comment]
fgxanstin@gmail.com

**Comment by Ariel-Thomas** [comment]
Alright, hit that email with a change of password request.

**Comment by Ariel-Thomas** [comment]
Let me know if everything looks good so I can close this issue.

**Comment by Ariel-Thomas** [comment]
Well, actually, I'll push a fix before that.

**Comment by xanstin** [comment]
Ok looks good so what is the right way to change my email ? Did I do something wrong?

**Comment by Ariel-Thomas** [comment]
No, I just accidentally rigged the delete button up to the update button  I've just pushed a fix and I'd like you to test it if you don't mind. You'll know it's the fixed version if you see the cancel my account button as a separate button way down.

**Comment by xanstin** [comment]
Crosses fingers .....it worked your awesome man.

**Comment by Ariel-Thomas** [comment]
Cool, seems to be working for my accounts too.

You'll need to update any user preferences you had. Those are probably borked.
