### ISSUE TITLE
Any Interest in a Trading Post?

### ISSUE THREAD

**Issue by Ariel-Thomas** [Ariel-Thomas/adventurers-league-log#77]
Seems like there's a lot of people trading magic items from the site, but it might be just as well to cut out the middleman. Is there any interest in a Trading Post section where you can post magic items for trade and  search for items other users have posted? I probably wouldn't handle any of the transferring myself, just enabling contact between the two parties, at least for now.

**Comment by tjclayton** [comment]
There are already Facebook groups for this, etc. Personally, I think this is scope creep.

**Comment by rooneg** [comment]
Yeah, I think in practice most people who are trading items are doing it either with local friends or via the facebook group.

**Comment by Ariel-Thomas** [comment]
Hm. Feature creep is definitely ab issue.  Maybe I spawn off a separate
but related site. Microservices and all that.

Does a site like this already exist? It seems like one should.

**Comment by Ariel-Thomas** [comment]
Alright, looks like there's not much interest, so I'mma close this. Thanks for the feedback.
