### ISSUE TITLE
More columns for DM logs

### ISSUE THREAD

**Issue by Troacctid** [Ariel-Thomas/adventurers-league-log#79]
This season's DM quests add a lot of new ways to get renown, so it would be nice to have that be visible without having to click on the entry.

It could also be nice to get a Missions column and maybe Magic Items as well, if space permits (which it might not).

**Comment by Ariel-Thomas** [comment]
Magic Items could get kind of messy but the other two do make sense... Can you explain to me why you'd want magic items on the list? I might have another solution.

**Comment by Troacctid** [comment]
I was thinking it might be useful information to have at a glance when scrolling through the logs. There probably isn't room for it though.
