### ISSUE TITLE
DM rewards date assigned

### ISSUE THREAD

**Issue by brustmlj** [Ariel-Thomas/adventurers-league-log#8]
Missed in the breakup.  There need to be a date on which the DM reward is assigned to a character in order for the log to be generated correctly.  DM rewards do not all go at the end.  Nor should they use the date the reward was earned.

**Comment by Ariel-Thomas** [comment]
Why would the date assigned matter?

**Comment by brustmlj** [comment]
In order to generate a proper log sheet.  It affects the level which an adventure is played on the log sheet.  If the award are all at the end then the logs generated will not be correct.  It may say that a Tier 2 mod was played by a Tier 1 character.  Or a Tier 3 mod was played by a Tier 2 character.

 

I often use a DM reward on a character as a specific time to bump tiers.  The DM reward needs to be reflected on the log sheet when it is applied to make the generated log correct.

 

Finally generated logs should remain in a constant order over time.  I should only be adding stuff to the end of the log not reordering the log.

**Comment by Ariel-Thomas** [comment]
> Finally generated logs should remain in a constant order over time.  I should only be adding stuff to the end of the log not reordering the log.

Just to clarify: And adding this date assigned would maintain that order?

**Comment by brustmlj** [comment]
There should be a date assigned field in the DM Rewards record.  Right now when you highlight Include DM rewards they just all go at the end of the printout.  So the order over time is not maintained.  If a add a new log it will occur in the log before the DM rewards.

 

What I think need to happen is that the date assigned field need to be used as the sort field on the character logs.  So that the DM rewards appears in the correct location of the character log.
