### ISSUE TITLE
Adding total PC level to Character Selections screen

### ISSUE THREAD

**Issue by xanstin** [Ariel-Thomas/adventurers-league-log#80]
Maybe as an enhancement add total PC level to Character selection screen to see at a glance what level the characters in the stable are at versus having to go into each one.

**Comment by Ariel-Thomas** [comment]
The Class field is intended to solve this already.

**Comment by xanstin** [comment]
Right that's a manual way to add it or to show multiclassing. I was referring to an automated total number based off of total xp

**Comment by kenibrewer** [comment]
I agree with xanstin. The Class field requires manual updating (which I always forget to do). I would prefer to have a column with just the total character level but still keep the Class field as is. That would make things really easy for single class characters (no need to update class field at all). For multi-classed characters it would let me be slightly lazier too. I would probably just put "Paladin/Warlock" in the class field and not sweat the details of how exactly my automatically-updated character levels are distributed between the two.

**Comment by tjclayton** [comment]
The existing approach seems perfectly fine to me. You still need to keep the Class field updated so that it reflects properly on the printed adventure log. It looks like this is closed as well.

**Comment by kenibrewer** [comment]
I've actually never printed my log sheets, and I would prefer it if I could be lazy enough to only update the Class field when I multi-class for the first time, or if I ever do end up printing a copy of the log sheets. 

Xanstin closed this thread (prematurely in my opinion), I think it should be reopened because this is still a potential enhancement worth discussing.

**Comment by tjclayton** [comment]
It's probably better to keep things simple. Right Ken?

The standard AL log sheet that is used to track to track your character requires classes and associated levels to be listed. This log is meant to mirror that from what I can tell.

By all means re-open it. I would personally rather see some of the other enhancements implemented first.

**Comment by xanstin** [comment]
actually I just realized I closed it lol wasn't on purpose

**Comment by xanstin** [comment]
To keep this more in line with the feedback perhaps it would be better to add a total level column
![levels](https://user-images.githubusercontent.com/26841771/29242523-15547376-7f5d-11e7-9e1f-df305512b29e.png)
 on characters page and still leave class/level option as it is now for multiclass. This would give you at a glance for those with a lot of PC's which pc you can take to a module since that only cares about total level.
