### ISSUE TITLE
Magic Item D&D 5e

### ISSUE THREAD

**Issue by DLucena1888** [Ariel-Thomas/adventurers-league-log#88]
To make a magic item you must have the item's recipe to be created, out of money, time and level. No D & D 5e. Or just need the level, money, and time to create magic items in D & D 5e?
According to a master should aver a recipe so the character can create a magic item!

**Comment by tjclayton** [comment]
I am not 100% sure what you are saying, but if it is about creating magic items, you cannot do that in Adventurers League play. Adventurers League is standardized play with a specific set of rules.

**Comment by DLucena1888** [comment]
thanks for the answer tjclayton
I from brazil.
 Sorry, I'm not very good with English. 
 Example if I want to do a magic item (+1 armor) I have to have a recipe that teaches my character the create this +1 armor or I only create the item.With pg and time

**Comment by krmaxwell** [comment]
This is probably the wrong forum to ask this as it doesn't relate to the web site www.adventurersleaguelog.com.

**Comment by Sansd20** [comment]
You may want to try https://www.reddit.com/r/dndnext

**Comment by Ariel-Thomas** [comment]
Thanks for the assists while I've been away @krmaxwell and @Sansd20
