### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rogue-of-gallifrey** [Ariel-Thomas/adventurers-league-log#90]
Just a suggestion, I was directed here by another user.

For the Game Log Entries, add 2 columns of 6 fields to record the other players and their characters that you played with.

Could also include that in DM Log to record players you DMed for. Though I would include 7 fields in that case.

**Comment by Ariel-Thomas** [comment]
Sorry I've been a while getting back.

What's the purpose of this? It's not required by the AL and I don't see it being used all that often.
