### ISSUE TITLE
Print Log Sheets show magic items that are not counted

### ISSUE THREAD

**Issue by xanstin** [Ariel-Thomas/adventurers-league-log#92]
I noticed that even though you unchecked magic item counts and the webpage shows the correct number. The printed PDF sheet shows all items with or without the check.

**Comment by kenibrewer** [comment]
Does it simply show the item (which I imagine a printed logsheet should), or does it result in an incorrect magic item count?

**Comment by xanstin** [comment]
Here is an example. The Boots of the Winterland is marked to not show up in count since its the initiate item.  But in the Paper printed log it shows up as an item towards count.
![item count error](https://user-images.githubusercontent.com/26841771/29004585-b47cca68-7a97-11e7-8ed4-49a20d5b177a.png)

**Comment by Ariel-Thomas** [comment]
Hrm. I think I know what's going on here. Should be an easy fix. Good catch.
