### ISSUE TITLE
Paladins MUST be fixed ASAP (spell scaling is 0)

### ISSUE THREAD

**Issue by KazduI** [Ariel-Thomas/adventurers-league-log#93]
Hello, I play a paladin named Kazdul, my gear is spell power oriented (380 SP) and looks like it's worthless due to some major disabling/crippling/nerfing, or what have you, on paladins.
Looks like 90% of abilities/spells and chance on hit magic damage items are not scaling at all with SP,
Examples below:
1. **8/8 T2 paladin set** is +60 to 66 holy damage to all judgements, at the moment it does not scale at all, should scale with around **40%** spell damage.
2. **Consecration** does not scale at all, should scale with around **25%**.
3. Trinkets like **Darkmoon Card: Maelstrom** and **Heart of Wyrmthalak** at the moment does not scale at all, should scale with around **25-30%** of my spell damage.
4. **Sulfuras, Hand of Ragnaros** not scaling at all, should be around **25-30%**.
5. **Force Reactive Disk** (engineering) at the moment does not scale at all, should scale with **~25%**.
6. **Seal of Righteousness** does not scale correctly, the talent **"Improved Seal of Righteousness"** does not work at all.
7. Enchants like **Lifestealing** and **Fiery Blaze** (AoE fire damage) should also scale with around **30%** from SP.
8. Eye for an Eye does not scale, should scale with 40% of paladin SP and 40% from enemy SP if I remember correct.

And lastly the Reckoning ability is bugged a lot, I have experienced few reasons, that should not be, to make my stacks disappear:
1. Disarm.
2. Sometimes from multiple CC effects on you such as stun + poly or fear + poly.
3. Switching weapons.
4. Leaving duel.

I beg you to take a look at this since it's game breaking for the class, this issue is a fact from more than 6 months. Thank you for your time and hope you can fix us. =)

**Comment by kenibrewer** [comment]
Kazdul, it sounds like your providing feedback on the the World of Warcraft Paladin class. This Github is used to report bugs and request features for adventurersleaguelog.com which is a tool to help players keep records for Dungeons & Dragons Adventurers League Organized Play. Might I recommend the Blizzard forums for your post?

**Comment by krmaxwell** [comment]
:-1:

**Comment by Ariel-Thomas** [comment]
Well, this is a pretty weird thing to come back to.
