### ISSUE TITLE
Trade logs can't take fractional gp

### ISSUE THREAD

**Issue by Troacctid** [Ariel-Thomas/adventurers-league-log#98]
Inputting a fractional value causes a validation error, as seen in this example, where an unlucky character with a squalid lifestyle has trouble logging their gold.
![image](https://user-images.githubusercontent.com/26239760/30187776-e61752ee-93df-11e7-82f5-01e25defa3e2.png)

**Comment by dalesd** [comment]
I had this exact problem come up recently. I rounded -1.5 GP to -2.

**Comment by Yubelchen** [comment]
Have the same problem since i sjoined here, strangly enough it works with Game Logs, i´m using those and call the Adventure 'TRADE' until it is fixed, pretty annoying.
