### ISSUE TITLE
Add season 7 content

### ISSUE THREAD

**Issue by krmaxwell** [Ariel-Thomas/adventurers-league-log#99]
When you get a chance, it would be great to have the Season 7 adventures added. You can see the full list  of what's been announced so far at http://dndadventurersleague.org/dm-quests/quest-of-the-week/ (and probably other places too).

**Comment by Troacctid** [comment]
I believe it's pulled from the Content Catalogue, which has yet to be updated with the new adventures.

**Comment by Ariel-Thomas** [comment]
I have done this. Sorry it was like a month late. I'll try to plan better for it in the future.
